### ISSUE TITLE
TST Collapsed Tree Space

### ISSUE THREAD

**Issue by Zelmanyr** [drannex42/linux-utils#1]
Hi,

I really like what you did with Tree Style Tab ! An issue I have with your configuration is that when I collapsed a tree the space beneath it where the children tabs are doesn't collapsed, It is an empty space now. Can you tell me how I can disable this please ? In this case, I would like to have the default behavior of Tree Style Tab meaning collapsing the tree without an empty space under the parent tab.

Thank you.

**Comment by drannex42** [comment]
You should update to the latest version of the CSS files, v12020. 03.05 for tresstyletabs.css. I would also suggest using the json config file, but I don't believe it's required. I noticed this issue yesterday and updated sometime last night, hope that fixes the issue for you! If it doesn't let me know and I'll take a look.  ---- On Sat, 06 Mar 2021 15:38:03 -0600  notifications@github.com  wrote ----
Hi,
I really like what you did with Tree Style Tab ! An issue I have with your configuration is that when I collapsed a tree the space beneath it where the children tabs are doesn't collapsed, It is an empty space now. Can you tell me how I can disable this please ?
Thank you.

**Comment by Zelmanyr** [comment]
Hi,

The thing is your userChrome.css doesn't work well for me : https://imgur.com/a/ff2geiC
So I tweaked a bit your userChrome.css even though I don't know anything about css (just copy and paste from your css file and tree style tab wiki). But in both cases the space is still there and empty. 
I believe the issue is in the configuration of tree style tab ?

**Comment by drannex42** [comment]
I just pushed some updates to treestyletabs.css and userChrome.css (v12020.03.06) - try those.

The rest of your issues with the Firefox UI may be due to some other optional modifications I put into my userChrome, so remove everything below the comment /* OTHER CUSTOM OPTIONS */ in the file. 

Could you enable the bookmarks bar for me and tell me what happens (ctrl+shift+b) I have noticed it causes some issues if the bookmark bar isn't present.. And just to be sure - you are loading the treestyletabs.json file into your TST addon right? (manage extensions > preferences > scroll all the way down to "load" config at the bottom of the page)

**Comment by Zelmanyr** [comment]
With your newest css file it's kind of working : https://imgur.com/a/q8UZNXj

But I don't have the icon to switch to the bookmark panel.

Anyway, I will switch to sidebery because it's snappier and bookmark are already implemented.

Thank you for your work.

**Comment by drannex42** [comment]
The reason it's not showing the sidebar panel switcher is because you need to have the bookmark bar enabled under the address bar. It's a known bug that I'm trying to figure out how to correct.  ---- On Sun, 07 Mar 2021 17:55:40 -0600  notifications@github.com  wrote ----
With your newest css file it's kind of working : https://imgur.com/a/q8UZNXj
But I don't have the icon to switch to the bookmark panel.
Anyway, I will switch to sidebery because it's snappier and bookmark are already implemented.
Thank you for your work.

**Comment by drannex42** [comment]
If you want to use this without the bookmark bar enabled, add this to your userChrome.css

```
#sidebar-box {
--menubar-height: -40px !important;
}
```

This will show the switcher buttons.
