### ISSUE TITLE
Mac Sidebar

### ISSUE THREAD

**Issue by TwisterMc** [drannex42/linux-utils#2]
On Mac, the sidebar Needs some padding, however I'm not sure how that'll effect other OSs.

```
#sidebar-header {
  padding-top: 30px !important;
}
```

**Comment by TwisterMc** [comment]
After some thought & testing, I'd rather add some padding above the URL bar and then less on the sidebar-header.

```
#nav-bar-customization-target {
	padding-top: 5px !important;
}

#sidebar-header {
  padding-top: 20px !important;
}
```

**Comment by drannex42** [comment]
I am not a Mac user, and this causes issues in padding for me (on Windows, and Linux). I'll keep this issue open, so others on Mac can find it. 

Is there any Mac-related `data-*` tag in the `<html"id="main-window" ... >` tag of the browser? I don't see one for Linux, but if there is one for Mac we could create a specific rule for that OS. I see on mine a "macanimation" attribute, so that won't work.

**Comment by TwisterMc** [comment]
I was wondering the same thing and it appears that there is:
https://www.reddit.com/r/FirefoxCSS/comments/mtqs28/os_specific_styles/
